#adapted from example in docker documentation
version: '3'

services:
  web:
    restart: always
    build: .
    volumes:
       - .:/code
    links:
       - redis:redis
    expose:
       - 8000
    user: 1001:1002 ## needed for linux
    environment:
       - GOOGLE_APPLICATION_CREDENTIALS=/code/mysite/cins465-cloudkey.json
    working_dir: /code/mysite
   #  command: python manage.py runserver 0.0.0.0:8000
    command: daphne -b 0.0.0.0 -p 8000 mysite.asgi:application

  redis:
   image: redis:latest
   expose:
      - 6379

  wasm:
    build: ./wasm/
    environment:
       - USER=bryan
    working_dir: /code/wasm-test/myproject/
    # user: 1001:1002 ## needed for linux
    volumes:
      - .:/code

#   nginx:
#    restart: always
#    build: ./nginx/
#    volumes:
#        - ./mysite/static/:/static
#    depends_on:
#       - web
#    ports:
#       - 80:80
#       - 443:443
#    links:
#       - web:web

  caddy:
   image: caddy:latest
   restart: unless-stopped
   depends_on:
     - web
   links:
     - web:web
   ports:
     - "80:80"
     - "443:443"
   volumes:
     - $PWD/Caddyfile:/etc/caddy/Caddyfile
     - $PWD/mysite/static:/srv/static/
     - caddy_data:/data
     - caddy_config:/config

volumes:
 caddy_data:
 caddy_config:
