# Generated by Django 3.2.7 on 2021-09-16 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_suggestionmodel_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suggestionmodel',
            name='author',
        ),
    ]
